### ISSUE TITLE
[Meta] Wrapping a full calibration sequence

### ISSUE THREAD

**Issue by yimuchen** [UMDCMS/SiPMCalibControl#21]
Standardize a turn-key solution for running full calibration sequence, including case handling for when certain routines fails either for full tile boards or for single channels.

This should include 2 big parts:
- A "system" calibration: getting adjustment parameters of the gantry system
- A "tileboard" calibration: extracting data for the individual SiPM characterization.

The results of a tileboard calibration will need to be bundled with the system calibration to make sense for the full analysis program.

Program-wise we need the following components (Maybe we want to fully separate out the GUI from the CLI in this case?)

- [ ] An extensible representation of a "tileboard" (partially implemented in `cmod/board.py`, but this might not be the best path forwards) 
  - [X] Data describing tileboard readout channel positions
  - [ ] Extensible metadata columns for (tileboard type, part ID number, calibration timestamp information ext) 
  - [ ] Logs for which calibration sequences has been carried out (for a give calibration sequence), and which files are corresponding to a certain calibration sequence.

- [ ] An extensible representation of what a "calibration sequence" is (should be more than just a list of commands)
  - [ ] An interface for initiating and monitoring a calibration sequence (partially implemented in the GUI) 
  - [ ] The functionality to rerun/extend "bad" calibration sequences.
